[en]
    label  = "English"
    title  = "Hugo Theme Stack"
    weight = 1

    [en.params.sidebar]
        subtitle = "Card-style Hugo theme designed for bloggers"

[zh]
    label  = "简体中文"
    title  = "硬件学习ing"
    weight = 2

    [zh.params.sidebar]
        subtitle = "为国为民为天下"

[zh-hant-tw]
    label  = "正體中文"
    title  = "硬件学习ing"
    weight = 3

    [zh-hant-tw.params.sidebar]
        subtitle = "为国为民为天下"

[ja]
    label  = "日本語"
    title  = "硬件学习ing"
    weight = 4

    [ja.params.sidebar]
        subtitle = "为国为民为天下"
